version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_SQS_NAME_QUEUE: ${AWS_SQS_NAME_QUEUE}
    ports:
      - "4000:4000"